version: "3.9"
services:
  web:
    build: .
    container_name: botapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:$DB_IN_PORT/postgres
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=$PGDATA
    ports:
      - "$DB_IN_PORT:$DB_OUT_PORT"
    volumes:
      - /var/lib/postgresql/data
    restart: always
