server:
  servlet:
    context-path: /api
#logging:
#  level:
#    ROOT: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DB_OUT_PORT}/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true
telegram:
  name: ${BOT_NAME}
# @BotFather
  token: ${BOT_TOKEN}
# открытие для меня - к ID чата нужно добавлять 100
# https://github.com/GabrielRF/telegram-id#web-group-id
  chanel-id:  ${PRIVATE_CHANNEL}
  support:
# @getidsbot - get admin id
    chat-id: ${SUPPORT_ID}
